### ISSUE TITLE
Toggling loopMode disables background colour on hover

### ISSUE THREAD

**Issue by girlflux** [FernandoEsparrinha/h0b0-redo#4]
### Toggling `loopMode` disables background colour on hover.

There is a conflict between the CSS declarations for the `.toggle` and `.button` elements of the UI and the JS that controls the active state display. The JS declaration overwrites the CSS.

The JS declarations target specifically the `background` if `loopMode` is either active or inactive. This is correct. However, the `:hover` is also overwritten to become transparent.

In `style.css`:

![style](https://user-images.githubusercontent.com/19334994/98282330-fbcc7200-1f95-11eb-8aec-180858081062.JPG)

In `GuiController.js`:

![guicontroller](https://user-images.githubusercontent.com/19334994/98283571-bf9a1100-1f97-11eb-8618-6f8339bc49e0.JPG)

**Comment by diogoterremoto** [comment]
I think this happens because JavaScript controller is styling the element using the style attribute, which has prevalence over stylesheet declarations. Ideally, style changes triggered by JS should be made with CSS classes, and not via the style attribute, as to organize the code and prevent [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) issues like this one.

If I'm understanding the goal correctly, this add this CSS declarations:
```
.toggle, .button {
    background-color: transparent;
}

.toggle.loopMode, .button.loopMode, .toggle:hover, .button:hover {
    background-color: var(--button-bg-active);
}
```

and then, add/remove the `loopMode` class when appropriate [via JS](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList).

**Comment by girlflux** [comment]
### Fixed ✅


**GuiController.js**
```
if (loopMode) {
    loopButton.addClass('loopMode')
}
else {
    loopButton.removeClass('loopMode')
}
```

**style.css**

```
.loopMode, .loopMode:hover {
    background: var(--button-bg-active);
}
```
